// const now= new Date();
// console.log(now);
// console.log(now.toString());
// console.log(now.toISOString());
// console.log(now.toLocaleString());
// console.log(now.getDate());
// console.log(now.getDay());
// console.log(now.getMonth());
// console.log(now.getFullYear());
// console.log(now.getTime());
// console.log(now.getHours());
// console.log(now.getMinutes());
// const now=new Date(2026,2,17,21,5,6,5);
// console.log(now);
const now =Date.now();
const dates=new Date(-12312321);
// const dates=new Date(1773763944780);
// console.log(dates.toString());
console.log(dates);