let marks=[100,50,70,80];
console.log(marks);
console.log(marks.length);
let arr=[100,50,"renu",true];
console.log(arr);
console.log(arr[2]);
console.log(typeof arr);
// arr[1]=50;
arr.push(90);
console.log(arr);
arr.pop();
console.log(arr);
arr.unshift(10);
console.log(arr);
arr.shift();
console.log(arr);
const arr1=[10,30,50,80];
const arr6=["renu",11,true];
arr1.push(arr1);
console.log(arr1);
const arr3=[9,4,false];
const arr4=arr1.concat(arr6,arr3);
console.log(arr);
for(let i=0;i<arr1.length;i++){
    console.log(arr1[i]);
}
for(let num of arr1){
    console.log(num);
}
let arr2 =[10,20,30,40,50];
let arr5=arr1;
arr3.push(30);
console.log(arr1);
console.log(arr1.slice(1,3));
console.log(arr1);
console.log(arr1.splice(1,3));
console.log(arr1);
const Name =["alice","charlie","renu","bob"];
console.log( Name.toString() );
// console.log(Name.join(" "));
// console.log(Name.indexOf("bob"));
Name.sort();
console.log(Name);
Name.reverse();
console.log(Name);
const num=[102,67,54,2,76];
num.sort((a,b)=>a-b);
console.log(num);
num.sort((a,b)=>b-a);
console.log(num);
const arr10 =[10,30,50,[40,60,11],90];
console.log(arr10[3][1]);
console.log(arr10[3]);
const a =arr10.flat(2);
console.log(a);
const b =[10,309,"renu",9.3,true];
console.log(b["1"]);
b.name="mohan";
console.log(b);
