marks=[34,45,57,89,23]
marks.append(96)
print(marks)
marks.sort()
print(marks)
marks.remove(89)
print(marks)
marks.reverse()
print(marks)
marks.insert(3,89)
print(marks)
marks.pop(2)
print(marks)
marks[4]=78
marks[2]=99
print(marks)
food=["mango","apple","panner","patato"]
print(food[2])
food[2]="banan"
print(food)
print(food[1:4])
print(marks[2:5])
print(min(marks))
print(max(marks))
print(min(food))
print(max(food))