myTuple = (78,90,75)
studentTuple =("renu","riya","siya")
emptytuple = ()
singletuple = (3)
print(studentTuple[1])
print(type(studentTuple))
print(type(emptytuple))
print(type(singletuple))
print(studentTuple.index("riya"))
print(studentTuple.count("renu"))